all: super-pong-client super-pong-server

super-pong-client: super-pong-client.c
	gcc -o super-pong-client lib.c super-pong-client.c -lncurses

super-pong-server: super-pong-server.c
	gcc -o super-pong-server lib.c super-pong-server.c -lncurses